import * as XLSX from 'xlsx';
import type { ReconciliationCheck, ReportMeta } from './report-context';
import { renderHtmlToPdf } from '../pdf.service';

/**
 * Turning a report into a file.
 *
 * Exports are built here, on the server, from the same filters that produced
 * the on-screen result - never from rows posted back by the browser. A client
 * that can submit its own report data can submit any numbers it likes, and the
 * resulting spreadsheet would carry the organization's letterhead over figures
 * the server never computed.
 *
 * All three formats come from one description of the report, so a CSV, a
 * spreadsheet and a PDF of the same run cannot disagree with each other.
 */

export interface ExportColumn<Row> {
  header: string;
  value: (row: Row) => string | number | null | undefined;
  /** Right-align and format as money in the spreadsheet. */
  money?: boolean;
}

export interface ExportSection {
  title: string;
  headers: string[];
  rows: Array<Array<string | number>>;
}

export interface ReportExport<Row> {
  meta: ReportMeta;
  /** Per-currency summary tables, printed above the detail. */
  sections: ExportSection[];
  columns: ExportColumn<Row>[];
  rows: Row[];
  reconciliation: ReconciliationCheck[];
}

const escapeHtml = (value: unknown): string =>
  String(value ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');

const slug = (value: string): string =>
  value
    .trim()
    .replace(/[^a-zA-Z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '') || 'Report';

/**
 * A name a person can read, that still cannot collide.
 *
 * Sorts by date in a downloads folder, says what it is and when it was run.
 */
export function exportFileName(meta: ReportMeta, extension: string): string {
  const now = new Date();
  const pad = (n: number) => String(n).padStart(2, '0');
  const stamp =
    `${now.getFullYear()}-${pad(now.getMonth() + 1)}-${pad(now.getDate())}` +
    `-${pad(now.getHours())}${pad(now.getMinutes())}-${pad(now.getSeconds())}`;
  return `${slug(meta.reportName)}-${stamp}.${extension}`;
}

/** The provenance block every format carries. */
function metaLines(meta: ReportMeta): Array<[string, string]> {
  return [
    ['Report', meta.reportName],
    ['As at', new Date(meta.asOfDate).toLocaleString('en-GB')],
    [
      'Period',
      meta.dateRange.from
        ? `${new Date(meta.dateRange.from).toLocaleDateString('en-GB')} to ${new Date(
            meta.dateRange.to ?? meta.asOfDate
          ).toLocaleDateString('en-GB')}`
        : 'All time',
    ],
    ['Timezone', meta.timezone],
    ['Filters', Object.entries(meta.filters).map(([k, v]) => `${k}: ${v}`).join('; ')],
    ['Generated', new Date(meta.generatedAt).toLocaleString('en-GB')],
    ['Generated by', meta.generatedBy?.name ?? 'Unknown user'],
  ];
}

// ---------------------------------------------------------------- CSV
export function toCsv<Row>(report: ReportExport<Row>): string {
  const quote = (value: unknown) =>
    `"${String(value ?? '').replace(/"/g, '""')}"`;

  const lines: string[] = [];

  for (const [label, value] of metaLines(report.meta)) {
    lines.push(`${quote(label)},${quote(value)}`);
  }
  lines.push('');

  for (const section of report.sections) {
    lines.push(quote(section.title));
    lines.push(section.headers.map(quote).join(','));
    for (const row of section.rows) lines.push(row.map(quote).join(','));
    lines.push('');
  }

  lines.push(quote('Detail'));
  lines.push(report.columns.map(column => quote(column.header)).join(','));
  for (const row of report.rows) {
    lines.push(report.columns.map(column => quote(column.value(row))).join(','));
  }

  if (report.reconciliation.length > 0) {
    lines.push('');
    lines.push(quote('Reconciliation'));
    lines.push(['Formula', 'Currency', 'Expected', 'Actual', 'Difference', 'OK'].map(quote).join(','));
    for (const check of report.reconciliation) {
      lines.push(
        [
          check.formula,
          check.currency,
          check.expected,
          check.actual,
          check.difference,
          check.ok ? 'YES' : 'NO',
        ]
          .map(quote)
          .join(',')
      );
    }
  }

  // The BOM is what makes Excel open a UTF-8 CSV without mangling accents.
  return `﻿${lines.join('\n')}`;
}

// --------------------------------------------------------------- XLSX
export function toXlsx<Row>(report: ReportExport<Row>): Buffer {
  const workbook = XLSX.utils.book_new();

  // Sheet 1: what this is a report of, and the headline figures.
  const summaryRows: Array<Array<string | number>> = [];
  for (const [label, value] of metaLines(report.meta)) {
    summaryRows.push([label, value]);
  }
  summaryRows.push([]);

  for (const section of report.sections) {
    summaryRows.push([section.title]);
    summaryRows.push(section.headers);
    for (const row of section.rows) summaryRows.push(row);
    summaryRows.push([]);
  }

  if (report.reconciliation.length > 0) {
    summaryRows.push(['Reconciliation']);
    summaryRows.push(['Formula', 'Currency', 'Expected', 'Actual', 'Difference', 'OK']);
    for (const check of report.reconciliation) {
      summaryRows.push([
        check.formula,
        check.currency,
        check.expected,
        check.actual,
        check.difference,
        check.ok ? 'YES' : 'NO',
      ]);
    }
  }

  const summarySheet = XLSX.utils.aoa_to_sheet(summaryRows);
  summarySheet['!cols'] = [{ wch: 60 }, { wch: 22 }, { wch: 18 }, { wch: 18 }, { wch: 14 }, { wch: 8 }];
  XLSX.utils.book_append_sheet(workbook, summarySheet, 'Summary');

  // Sheet 2: the rows the summary is made of.
  const detail = [
    report.columns.map(column => column.header),
    ...report.rows.map(row => report.columns.map(column => column.value(row) ?? '')),
  ];
  const detailSheet = XLSX.utils.aoa_to_sheet(detail);
  detailSheet['!cols'] = report.columns.map(column => ({
    wch: Math.min(Math.max(column.header.length + 2, 12), 40),
  }));
  XLSX.utils.book_append_sheet(workbook, detailSheet, 'Detail');

  return XLSX.write(workbook, { bookType: 'xlsx', type: 'buffer' }) as Buffer;
}

// ---------------------------------------------------------------- PDF
export function toPrintableHtml<Row>(report: ReportExport<Row>): string {
  const meta = metaLines(report.meta)
    .filter(([, value]) => value)
    .map(
      ([label, value]) =>
        `<div class="meta-item"><span class="meta-label">${escapeHtml(label)}</span><span>${escapeHtml(value)}</span></div>`
    )
    .join('');

  const sections = report.sections
    .map(section => {
      /**
       * Align each column by what it holds, and align its heading the same way.
       *
       * This right-aligned every cell after the first and left the headings
       * left-aligned, so on a wide column a value sat at the far right while
       * its heading sat at the far left - "PAR1" appeared under "Loans", and
       * every figure looked like it belonged to the column after it. A column
       * is numeric when its values are numbers; text columns stay left.
       */
      const numeric = section.headers.map((_, index) =>
        section.rows.length > 0 &&
        section.rows.every(row => typeof row[index] === 'number')
      );
      const align = (index: number) => (numeric[index] ? 'text-right' : '');

      return `
      <div class="section">
        <div class="section-title">${escapeHtml(section.title)}</div>
        <table>
          <thead><tr>${section.headers
            .map((h, index) => `<th class="${align(index)}">${escapeHtml(h)}</th>`)
            .join('')}</tr></thead>
          <tbody>${section.rows
            .map(
              row =>
                `<tr>${row
                  .map(
                    (cell, index) =>
                      `<td class="${align(index)}">${escapeHtml(cell)}</td>`
                  )
                  .join('')}</tr>`
            )
            .join('')}</tbody>
        </table>
      </div>`;
    })
    .join('');

  const detailRows = report.rows
    .map(
      row =>
        `<tr>${report.columns
          .map(
            column =>
              `<td class="${column.money ? 'text-right' : ''}">${escapeHtml(column.value(row))}</td>`
          )
          .join('')}</tr>`
    )
    .join('');

  const failed = report.reconciliation.filter(check => !check.ok);

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>${escapeHtml(report.meta.reportName)}</title>
<style>
  * { box-sizing: border-box; }
  body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; padding: 16px; color: #1a1a1a; font-size: 10px; }
  h1 { font-size: 18px; margin: 0 0 4px 0; color: #0f4c3a; }
  .meta { display: grid; grid-template-columns: 1fr 1fr; gap: 2px 24px; margin: 10px 0 16px 0; padding-bottom: 10px; border-bottom: 2px solid #0f4c3a; }
  .meta-item { display: flex; justify-content: space-between; padding: 1px 0; border-bottom: 1px dotted #eee; }
  .meta-label { color: #666; margin-right: 12px; }
  .section { margin-bottom: 16px; page-break-inside: avoid; }
  .section-title { font-size: 11px; font-weight: 600; color: #0f4c3a; margin-bottom: 5px; }
  table { width: 100%; border-collapse: collapse; font-size: 9px; }
  th { background: #0f4c3a; color: #fff; padding: 5px; text-align: left; font-weight: 600; }
  th.text-right, td.text-right { text-align: right; }
  td { padding: 4px 5px; border-bottom: 1px solid #e5e7eb; }
  tr:nth-child(even) td { background: #f8fafc; }
  .text-right { text-align: right; }
  .warn { border: 1px solid #b91c1c; background: #fef2f2; color: #b91c1c; padding: 8px; border-radius: 4px; margin-bottom: 12px; }
  .footer { margin-top: 10px; padding-top: 6px; border-top: 1px solid #ddd; text-align: center; color: #888; font-size: 8px; }
  @page { size: A4 landscape; margin: 10mm; }
  @media print { body { padding: 0; } thead { display: table-header-group; } tr { page-break-inside: avoid; } .section:last-of-type { margin-bottom: 0; } }
</style>
</head>
<body>
  <h1>${escapeHtml(report.meta.reportName)}</h1>
  <div class="meta">${meta}</div>

  ${
    failed.length > 0
      ? `<div class="warn"><strong>This report does not reconcile.</strong> ${failed
          .map(
            check =>
              `${escapeHtml(check.formula)} (${escapeHtml(check.currency)}): out by ${check.difference}`
          )
          .join('; ')}</div>`
      : ''
  }

  ${sections}

  <div class="section">
    <div class="section-title">Detail (${report.rows.length} record${report.rows.length === 1 ? '' : 's'})</div>
    ${
      report.rows.length > 0
        ? `<table>
      <thead><tr>${report.columns.map(c => `<th class="${c.money ? 'text-right' : ''}">${escapeHtml(c.header)}</th>`).join('')}</tr></thead>
      <tbody>${detailRows}</tbody>
    </table>`
        : '<p style="color:#888;font-style:italic">No records match these filters.</p>'
    }
  </div>

  <div class="footer">
    Generated ${escapeHtml(new Date(report.meta.generatedAt).toLocaleString('en-GB'))}
    by ${escapeHtml(report.meta.generatedBy?.name ?? 'Unknown user')}
    &middot; every total is stated in its own currency
  </div>
</body>
</html>`;
}

export async function toPdf<Row>(report: ReportExport<Row>): Promise<Buffer> {
  return renderHtmlToPdf(toPrintableHtml(report), { landscape: true });
}
